---

steps:

  - label: ":hammer: Test"
    plugins:
      - docker-compose#v2.5.1:
          run: "tests"
    agents:
      queue: "${AGENT_QUEUE}"

  - label: ":sparkles: Lint"
    plugins:
      - plugin-linter#v2.0.0:
          id: "envato/stop-the-line"
    agents:
      queue: "${AGENT_QUEUE}"

  - label: ":shell: Shellcheck"
    plugins:
      - shellcheck#v1.1.1:
          files:
            - "hooks/**"
    agents:
      queue: "${AGENT_QUEUE}"
