#!/usr/bin/env bash
set -euo pipefail

function plugin_read_config() {
  local var="BUILDKITE_PLUGIN_STOP_THE_LINE_$1"
  echo "${!var:-}"
}

function stop_the_line() {
  echo "--- :octagonal_sign: Stopping the line"
  case "$(plugin_read_config STYLE)" in
    pass) echo 'steps: []' | buildkite-agent pipeline upload --replace;;
    fail) exit 1;;
    *) echo 'style must be "pass" or "fail"' && exit 2;;
  esac
}

echo "--- Checking build meta-data"
key=$(plugin_read_config IF_KEY)
if [ -n "$key" ]; then
  anticipated_value=$(plugin_read_config IF_VALUE)
  actual_value=$(buildkite-agent meta-data get "$key" --default '')
  echo "$key: '$actual_value'"
  echo "'$anticipated_value'"
  if [ "$anticipated_value" = "$actual_value" ]; then
    stop_the_line
  fi
else
  key=$(plugin_read_config UNLESS_KEY)
  anticipated_value=$(plugin_read_config UNLESS_VALUE)
  actual_value=$(buildkite-agent meta-data get "$key" --default '')
  echo "$key: '$actual_value'"
  if [ "$anticipated_value" != "$actual_value" ]; then
    stop_the_line
  fi
fi
